### PR TITLE
Update WriteNode.js

### PR DESCRIPTION
**Pull request by adryyy**
There was a problem with update operation which: "Error: Update() requires either a single JavaScript object or an alternating list of field/value pairs that can be followed by an optional precondition. Input is not an object.".

### CODE REVIEW

**Comment by sichangi** [comment]
Interesting, Thanks for the heads up

I would propose you restructure it as such:

```javascript
case 'update':
case 'delete':
  this.firestore.collection(col).doc(doc)[op](payload)
   .then(handleSuccess)
   .catch(handleFailure)
case 'set':
  this.firestore.collection(col).doc(doc)[op](payload, opts)
   .then(handleSuccess)
   .catch(handleFailure)
```
cause the ``set`` option is the only one that supports the option parameter.

**Comment by adryyy** [comment]
I've tested your propose, and still get the same error as above.
Set, Add and Delete works properly.

**Comment by sichangi** [comment]
Kindly include the ``break;`` statement, I forgot to put it there.

**Comment by sichangi** [comment]
Although, I will have to test this on my own at some point.

**Comment by adryyy** [comment]
Yes, I've put it at first try :).

**Comment by sichangi** [comment]
This has been patched by this [commit](https://github.com/sichangi/node-red-contrib-cloud-firestore/commit/e75ffe0855102cf07068be4d21b90e577ce550e8)

**Pull request closed without merging**
