### PR TITLE
Allows custom snap handler

### LINKED ISSUE #27: Custom handler for realtime
Hi,

I have a hard time combining realtime requests and custom handler.

For the handler, I use de `deactivate` option and add a `.onSnapshot()` in a function node later, but a listener is added at [startup](https://github.com/sichangi/node-red-contrib-cloud-firestore/blob/master/src/Read/ReadNode.js#L23), multiplying the events.
But removing the `realtime` option force me to initiate the flow somehow.

One idea to conciliate all of this would be to return the [`QueryDocumentSnapshot`](https://firebase.google.com/docs/reference/js/firebase.firestore.QueryDocumentSnapshot) (not only the data), maybe in the `msg.firestore` object. Since I need to get the [`ref`](https://firebase.google.com/docs/reference/js/firebase.firestore.QueryDocumentSnapshot#ref), then the parent, it would be OK.

Do you have other ideas? Any thoughts ?

### PR DESCRIPTION
**Pull request by JbIPS**
* Adds an UI section for handler edition
* Handles custom or default handler for all snap

Closes #27

### CODE REVIEW

**Comment by JbIPS** [comment]
Following that, I wonder if we should allow a custom handle via the input. That would be a bit redundant with the `disableHandler` but maybe more coherant with the UI.

**Comment by JbIPS** [comment]
Hello @sichangi!

Any news on this PR?

**Comment by sichangi** [comment]
Apologies on the delays,
Am currently reviewing this & I must say your implementation is pretty impressive. 👏

**Comment by sichangi** [comment]
I've reworked your code and added quite a bit of context support & restyling around it, so your code is the underlying implementation in the new release. Do check out the new version.
Thanks a ton. 👍

**Comment by JbIPS** [comment]
Thank you, I checked the new version, it's very nice (great job on the UI, that's not my area of expertise!)
But I noticed you totally removed the returning `Promise` in the Read main. That's very useful to set a status for example. Was that voluntary?

**Comment by sichangi** [comment]
Are you referring to these [ones](https://github.com/JbIPS/node-red-contrib-cloud-firestore/blob/master/src/Read/ReadNode.js#L90)?

If so, seems I didn't notice then cause I only copied over your Read.html.
I'll add them back in asap.

**Comment by JbIPS** [comment]
Yes, and mostly [this return](https://github.com/JbIPS/node-red-contrib-cloud-firestore/blob/master/src/Read/ReadNode.js#L103) and [this one](https://github.com/JbIPS/node-red-contrib-cloud-firestore/blob/master/src/Read/ReadNode.js#L114).
The function must *always* return a Promise so we can send the `done` signal when everything's over.

**Pull request closed without merging**
